# Generated by Django 5.2.7 on 2025-11-28 08:44

import django.db.models.deletion
import user_profile_service.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EncadrantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encadrant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_etudiant', models.CharField(blank=True, max_length=50)),
                ('niveau_etude', models.CharField(blank=True, max_length=50)),
                ('date_inscription', models.DateField(blank=True, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PieceJustificative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_piece', models.CharField(max_length=100)),
                ('nom_fichier', models.CharField(max_length=255)),
                ('fichier', models.FileField(upload_to=user_profile_service.models.upload_to_student)),
                ('date_depot', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='user_profile_service.studentprofile')),
            ],
        ),
    ]
